name: ci

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            name: chlog
            ext: tar.gz
          - os: macos-latest
            name: chlog
            ext: tar.gz
          - os: macos-latest
            name: chlog
            ext: tar.gz
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: chlog.exe
            ext: zip

    steps:
      - uses: actions/checkout@v2
      - name: Install rustup - ${{ runner.os }}
        run: |
          rustup set profile default
          rustup toolchain install stable --target ${{ matrix.target }}
          rustup update
          rustup default stable

      - name: Log versions
        run: |
          rustc --version
          cargo --version
          rustup --version

      - run: cargo check --release
      - run: cargo clippy --release -- -D warnings
      - run: cargo b --release --target ${{ matrix.target }}
      - run: cargo t --release
      - run: cargo fmt -- --check
      - run: du -h target/${{ matrix.target }}/release/chlog
