name: ci

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain: [stable, beta]

    steps:
      - uses: actions/checkout@v2
      - name: Install rustup - ${{ runner.os }}
        run: |
          cargo uninstall rustfmt
          rustup set profile default
          rustup toolchain install ${{ matrix.toolchain }}
          rustup update
          rustup default ${{ matrix.toolchain }}

      - name: Log versions
        run: |
          rustc --version
          cargo --version

      - run: cargo check --release
      - run: cargo clippy --release -- -D warnings
      - run: cargo b --release
      - run: cargo t --release
      - run: cargo fmt -- --check
