name: ci

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        fail-fast: false
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain: [stable, beta, nightly]

    steps:
    - uses: actions/checkout@v2
    - name: Install rustup in ${{ runner.os }}
      # run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain ${{ matrix.toolchain }} --profile default
      run: |
        rustup set profile default
        rustup toolchain ${{ matrix.toolchain }}
        rustup update

    - run: cargo check --release
    - run: cargo clippy --release
    - run: cargo b --release
    - run: cargo t --release
    - run: cargo fmt -- --check
