name: release

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  binary-crates:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            name: chlog
            ext: tar.gz
          - os: macos-latest
            name: chlog
            ext: tar.gz
          - os: macos-latest
            name: chlog
            ext: tar.gz
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: chlog.exe
            ext: zip

    steps:
      - uses: actions/checkout@v2
      - name: Install rustup - ${{ runner.os }}
        run: |
          rustup set profile default
          rustup toolchain install stable --target ${{ matrix.target }}
          rustup update
          rustup default stable

      - name: Log versions
        run: |
          rustc --version
          cargo --version
          rustup --version

      - run: cargo b --release --target ${{ matrix.target }}
      - name: Create archive
        shell: bash
        run: |
          cp target/${{ matrix.target }}/release/${{ matrix.name }} ${{ matrix.name }}
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            tar.exe -a -c -f chlog-${{ matrix.target }}.${{ matrix.ext }} ${{ matrix.name }}
          else
            tar -czvf chlog-${{ matrix.target }}.${{ matrix.ext }} ${{ matrix.name }}
          fi

      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: false
          fail_on_unmatched_files: false
          body:
            Please refer to
            [CHANGELOG.md](https://github.com/ydcjeff/chlog/blob/main/CHANGELOG.md)
            for details.
          files: |
            chlog-${{ matrix.target }}.${{ matrix.ext }}

      - name: Publish to crates.io
        if: matrix.os == 'ubuntu-latest'
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
